// SPDX-License-Identifier: GPL-3.0-or-later
{ Golden-oracle + analytic-limit tests for the Pearson VII lineshape.

  The curve is computed native-side by the same expression engine the Python
  sidecar mirrors (formula_points_set -> native_math_expr; the sidecar evaluates
  the ExpressionToNumpy translation). These tests pin the FORMULA:
    * golden values match numpy/scipy references (generated in
      Worker/py/test_fit_backend.py's companion check);
    * the FWHM property: value is A at the peak and A/2 at |x-x0| = sigma/2 for
      every m (that is what makes sigma the true FWHM);
    * the analytic limit m -> 1 reproduces a (peak-normalised) Lorentzian of the
      same FWHM (checkpoint G3).
  A shared formula bug would break at least one leg. }
unit testcase_pearson7;
{$mode objfpc}{$H+}
interface
uses Classes, SysUtils, fpcunit, testregistry,
  points_set, pearson7_points_set;
type
  TPearson7Test = class(TTestCase)
  private
    { Pearson VII value at x for the given parameters, via the curve's own
      native compute path (x0 = 10). }
    function P7(A, sigma, m, x: double): double;
    { Peak-normalised Lorentzian of FWHM = sigma, x0 = 10 - the m = 1 limit. }
    function LorentzPeakNorm(A, sigma, x: double): double;
  published
    procedure PeakEqualsAmplitude;
    procedure HalfMaximumAtHalfSigmaForEveryM;
    procedure GoldenValuesMatchNumpy;
    procedure LimitMEquals1IsLorentzian;
    procedure ExpressionIsNumpyAndNamesParameters;
  end;

implementation

const
  X0  = 10.0;
  EPS = 1e-6;

function TPearson7Test.P7(A, sigma, m, x: double): double;
var
  C: TPearson7PointsSet;
begin
  C := TPearson7PointsSet.Create(nil, X0);
  try
    C.AddNewPoint(x, 0);
    //  Position value is set by the app after placement (the constructor only sets
    //  its boundaries), so set it here as the app would.
    C.ValuesByName['x0'] := X0;
    C.ValuesByName['A'] := A;
    C.ValuesByName['sigma'] := sigma;
    C.ValuesByName['m'] := m;
    C.ReCalc;
    Result := C.PointYCoord[0];
  finally
    C.Free;
  end;
end;

function TPearson7Test.LorentzPeakNorm(A, sigma, x: double): double;
begin
  Result := A / (1 + Sqr(2 * (x - X0) / sigma));
end;

procedure TPearson7Test.PeakEqualsAmplitude;
begin
  AssertEquals('peak = A', 100.0, P7(100, 2, 2, X0), EPS);
end;

procedure TPearson7Test.HalfMaximumAtHalfSigmaForEveryM;
begin
  //  |x - x0| = sigma/2 must give A/2 regardless of m: that pins sigma = FWHM.
  AssertEquals('half-max m=2', 50.0, P7(100, 2, 2, X0 + 1.0), EPS);
  AssertEquals('half-max m=1', 50.0, P7(100, 2, 1, X0 + 1.0), EPS);
  AssertEquals('half-max m=0.7', 60.0, P7(120, 2, 0.7, X0 + 1.0), EPS);
end;

procedure TPearson7Test.GoldenValuesMatchNumpy;
begin
  //  Values generated by numpy (Worker/py) for the same formula.
  AssertEquals('golden 1', 14.166564366, P7(100, 2, 2, 12), 1e-6);
  AssertEquals('golden 2', 67.819091419, P7(80, 3, 3, 10.7), 1e-6);
  AssertEquals('golden 3', 91.147946308, P7(120, 1.5, 0.7, 10.4), 1e-6);
end;

procedure TPearson7Test.LimitMEquals1IsLorentzian;
var
  x: double;
begin
  x := 9.0;
  while x <= 11.0 do
  begin
    AssertEquals('Pearson7(m=1) = Lorentzian at x=' + FloatToStr(x),
      LorentzPeakNorm(100, 2, x), P7(100, 2, 1, x), 1e-6);
    x := x + 0.25;
  end;
end;

procedure TPearson7Test.ExpressionIsNumpyAndNamesParameters;
var
  C: TPearson7PointsSet;
  Expr: string;
begin
  C := TPearson7PointsSet.Create(nil, X0);
  try
    Expr := C.GetCurveExpression;
    AssertTrue('non-empty', Length(Expr) > 0);
    AssertTrue('power translated to **', Pos('**', Expr) > 0);
    AssertTrue('no native ^ left', Pos('^', Expr) = 0);
    AssertTrue('names A', Pos('A', Expr) > 0);
    AssertTrue('names sigma', Pos('sigma', Expr) > 0);
    AssertTrue('names m', Pos('m', Expr) > 0);
    AssertTrue('names x0', Pos('x0', Expr) > 0);
  finally
    C.Free;
  end;
end;

initialization
  RegisterTest('unit', TPearson7Test);
end.
