// SPDX-License-Identifier: GPL-3.0-or-later
{
This software is distributed under GPL
in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the warranty of FITNESS FOR A PARTICULAR PURPOSE.

@abstract(The version of the running binary, read from the binary itself.)

WHERE THE NUMBER COMES FROM. `Desktop/Fit.lpi` carries four numbers
(`MajorVersionNr`.`MinorVersionNr`.`RevisionNr`.`BuildNr`); the compiler embeds
them in the executable as a version resource, and the build script raises the
build number before every build. This unit reads the resource back out of the
file that is running, so what the user sees is what was actually built - not a
constant in the source that someone has to remember to edit, which is exactly
what the About box used to show ("version 1.1", four years out of date).

WHY READ THE BINARY rather than compile the number in. A constant is written
once and then diverges: the version resource is regenerated by the compiler on
every build, so reading it cannot go stale. It also means the same code reports
correctly in a build made by the IDE, by the script, or by CI.

WHY A MISSING RESOURCE IS NOT FATAL. Every other check in this codebase raises
(see `checks.pas`), but the version is decoration: it names the build in a title
bar and a dialog. A binary that cannot say which build it is, is still a binary
that fits curves correctly, and refusing to start over it would turn a cosmetic
gap into an outage. So the fallback is ANNOUNCED - logged once, at Warning, with
the reason - and the UI says the version is unknown rather than inventing one.
}
unit app_version;

{$mode objfpc}{$H+}

interface

{ The four numbers of the running binary, as in '1.2.0.1607'. Empty when the
  executable carries no readable version resource - callers show something
  else rather than pretending. Read once and cached: the answer cannot change
  while the process runs. }
function GetAppVersion: string;

{ What a window title says, by the convention every desktop follows: the
  document first, because that is what distinguishes one window from another in
  a task bar that truncates from the right; then the application and the build
  it is. ADocument empty gives just the application. }
function GetWindowTitle(const AAppName, ADocument: string): string;

implementation

uses
    SysUtils, fileinfo, log,
    //  Each reader registers itself with TFileVersionInfo from its own
    //  initialization section, so the executable format of THIS platform can
    //  only be read if its reader is linked. Darwin is tested before the general
    //  Unix case: it is a Unix, but its binaries are Mach-O, not ELF.
{$IF DEFINED(WINDOWS)}
    winpeimagereader;
{$ELSEIF DEFINED(DARWIN)}
    machoreader;
{$ELSE}
    elfreader;
{$ENDIF}

var
    { Read on the first call rather than in initialization: the log file is not
      open yet at unit-initialization time, so a warning raised there would be
      written nowhere. }
    FVersion: string = '';
    FVersionRead: boolean = False;

function ReadVersionFromBinary: string;
var
    Info: TFileVersionInfo;
begin
    Result := '';
    Info := TFileVersionInfo.Create(nil);
    try
        try
            //  No FileName assigned: the running executable is the default, and
            //  it is the only file whose version answers "which build is this?".
            Info.ReadFileInfo;
            Result := Info.VersionStrings.Values['FileVersion'];
        except
            on E: Exception do
                //  Announced, not swallowed. The usual cause is a project built
                //  with version info switched off, and the log is where that is
                //  diagnosed from a user's bug report.
                WriteLog('Version info could not be read from ' +
                    ParamStr(0) + ': ' + E.Message, Warning);
        end;
    finally
        Info.Free;
    end;

    if Result = '' then
        WriteLog('This binary carries no FileVersion; the version is reported ' +
            'as unknown.', Warning);
end;

function GetAppVersion: string;
begin
    if not FVersionRead then
    begin
        FVersion := ReadVersionFromBinary;
        FVersionRead := True;
    end;
    Result := FVersion;
end;

function GetWindowTitle(const AAppName, ADocument: string): string;
var
    App: string;
begin
    App := AAppName;
    if GetAppVersion <> '' then
        App := App + ' ' + GetAppVersion;
    if ADocument = '' then
        Result := App
    else
        //  ' - ' rather than an em dash: the title goes through window managers
        //  and task bars of three platforms, and this string has to survive all
        //  of them.
        Result := ADocument + ' - ' + App;
end;

end.
